name: 'Auto Merge'

on:
  workflow_dispatch:
  push:
    branches:
      - vc/**

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    uses: AkamaiETP/etp-reports-devops-tools/.github/workflows/reusable-auto-merge.yml@master
    with:
      auto_merge_app_id: ${{ vars.ETP_REPORTS_AUTO_MERGE_APP_ID }}
      source_branch: ${{ github.base_ref }}
    secrets: inherit
    
