name: Run Main

on:
  workflow_dispatch:

jobs:
  main_action:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12.7"

    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Clone another repository
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
          git clone https://github.com/islootsk/ExProjUtils.git

    - name: ls folder
      run: |
        ls -ltrh

    - name: Install requirements
      run: |
        pip install -e ExProjUtils


    - name: Run
      run: |
        python --version
        python3 --version
        python main.py